#Bài tập 1: Thao tác với ma trận  
**Lý thuyết**:  
NumPy cung cấp các công cụ mạnh mẽ để thao tác ma trận, bao gồm tính toán các định thức, tìm nghịch đảo và tính toán các giá trị riêng và vectơ riêng.
  
**Đề bài**:  
Tạo ma trận 5x5 ngẫu nhiên và thực hiện các thao tác sau:  
* Tính định thức (determinant) của ma trận.  
* Tìm nghịch đảo (transpose) của ma trận.  
* Tính các giá trị riêng (eigent value) và vectơ riêng (eigent vector) của ma trận.   
(Phần này sẽ liên quan tới đại số tuyến tính, mọi người có thể tự tìm hiểu để hiểu chi tiết về các khái niệm trên)

<details>
  <summary>Hint</summary>

```python
import numpy as np

# Generate a random 5x5 matrix
matrix = np.random.rand(5, 5)

# Compute determinant
det = np.linalg.det(matrix)

# Find inverse
inverse = np.linalg.inv(matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

```
</details>

In [4]:
# Your code here
import numpy as np
matrix = np.random.rand(5, 5)
print(matrix)
det = np.linalg.det(matrix)
print(det)
inverse = np.linalg.inv(matrix)
print(inverse)
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues, eigenvectors)

[[0.70159496 0.09843857 0.3645395  0.32362993 0.4087322 ]
 [0.20245393 0.2043484  0.49789438 0.30523379 0.83107812]
 [0.85600908 0.69739988 0.69119898 0.71408322 0.66767727]
 [0.77890276 0.54736394 0.62056792 0.27441622 0.37738589]
 [0.66999767 0.28850479 0.87677625 0.14825049 0.04944195]]
-0.04296680448376478
[[ 1.72468474 -0.7422489  -0.87909628  1.39966729 -0.59320986]
 [-2.06918075 -0.26809184  0.33989637  2.35049732 -0.91904829]
 [-0.70109222  0.70908071  0.1150615  -1.24411846  1.81923052]
 [ 0.23818405 -0.75132695  2.97482209 -3.97034053  0.79259208]
 [ 0.42117895  1.30112729 -1.03093255  1.28463637 -1.01050286]]
[ 2.46899095+0.j          0.37407444+0.j         -0.50841771+0.j
 -0.20682359+0.22074171j -0.20682359-0.22074171j] [[-0.32424304+0.j         -0.71695555+0.j          0.23868623+0.j
  -0.18556037-0.07140747j -0.18556037+0.07140747j]
 [-0.37217422+0.j          0.58982161+0.j          0.70553388+0.j
  -0.62729337+0.j         -0.62729337-0.j        ]
 [-0.63097232+0.j      

# Bài tập 2: Optimization
**Lý thuyết:**  
Gradient descent là một thuật toán tối ưu hóa được sử dụng để cực tiểu hóa hàm bằng cách di chuyển lặp đi lặp lại theo hướng dốc xuống.

**Đề bài:**  
Triển khai gradient descent sử dụng NumPy để tối ưu hàm số sau:
 $$ f(x) = x^2 + 5 \sin(x) $$
<details>
  <summary>Hint</summary>

```python
import numpy as np

def gradient_descent(x, learning_rate, iterations):
    for _ in range(iterations):
        gradient = 2*x + 5*np.cos(x)  # Đạo hàm riêng theo x
        x = x - learning_rate * gradient # Cập nhật tham số
    return x

# Khởi tạo các hyperparameters
x_initial = 5  # Input đầu vào
learning_rate = 0.1 # Tốc độ học
iterations = 100 # Số lần lặp

# Run gradient descent
minima = gradient_descent(x_initial, learning_rate, iterations)
```

</details>

In [5]:
# Your code here
import numpy as np

def gradient_descent(x, learning_rate, iterations):
    for _ in range(iterations):
        gradient = 2*x + 5*np.cos(x)  # Đạo hàm riêng theo x
        x = x - learning_rate * gradient # Cập nhật tham số
    return x

# Khởi tạo các hyperparameters
x_initial = 5  # Input đầu vào
learning_rate = 0.1 # Tốc độ học
iterations = 100 # Số lần lặp

# Run gradient descent
minima = gradient_descent(x_initial, learning_rate, iterations)

# Bài tập 3: Phân tích thống kê  
**Lý thuyết**:  
NumPy cung cấp các chức năng để phân tích thống kê, bao gồm tính toán giá trị trung bình (mean), trung vị (median), độ lệch chuẩn (standard deviation) và mối tương quan (correlation).  

**Đề Bài**:  
Thực hiện phân tích thống kê trên tập dữ liệu bai3.csv bằng NumPy:  
* Tính giá trị trung bình, trung vị và độ lệch chuẩn của tập dữ liệu.
* Tính toán ma trận tương quan giữa các biến khác nhau.
* Xác định các ngoại lệ trong tập dữ liệu bằng cách sử dụng điểm z.

<details>
  <summary>Hint</summary>

```python
  # Load dataset
  data = np.loadtxt('dataset.csv', delimiter=',')

  # Calculate mean, median, and standard deviation
  mean = np.mean(data, axis=0)
  median = np.median(data, axis=0)
  std_dev = np.std(data, axis=0)

  # Compute correlation matrix
  correlation_matrix = np.corrcoef(data, rowvar=False)

  # Identify outliers using z-scores
  z_scores = np.abs((data - mean) / std_dev)
  outliers = np.where(z_scores > 3)
```
</details>

In [12]:
# Your code here
# Load dataset
data = np.loadtxt('/content/bai3.csv', delimiter=',')

# Calculate mean, median, and standard deviation
mean = np.mean(data, axis=0)
median = np.median(data, axis=0)
std_dev = np.std(data, axis=0)

# Compute correlation matrix
correlation_matrix = np.corrcoef(data, rowvar=False)

# Identify outliers using z-scores
z_scores = np.abs((data - mean) / std_dev)
outliers = np.where(z_scores > 3)

ValueError: could not convert string 'Variable1' to float64 at row 0, column 1.

# Bài 4: Thao tác với tensor
Đề cho một tensor đại diện cho một hình ảnh thang độ xám. Thực hiện các thao tác sau:

1. Reshape: Reshape tensor thành một hình dạng khác trong khi vẫn đảm bảo tổng số phần tử không đổi.
2. Transpose: Transpose tensor dọc theo các trục được chỉ định.
3. Slice: Trích xuất một tập hợp con của tensor bằng cách cắt dọc theo các kích thước được chỉ định.
4. Concatenate: Concatenate nhiều tensor dọc theo các trục được chỉ định.
5. Các phép toán theo phần tử: Thực hiện các phép toán theo phần tử như cộng, trừ, nhân và chia với các giá trị vô hướng hoặc các tensor khác.
6. Hoạt động rút gọn: Thực hiện các hoạt động rút gọn như tính tổng, trung bình, tối thiểu và tối đa dọc theo các trục được chỉ định.
7. Indexing: Truy cập các phần tử riêng lẻ hoặc các tensor phụ bằng cách sử dụng các chỉ số nguyên hoặc boolean mark.

<details>
  <summary>Hint</summary>

  ```python
    # 1. Reshape the tensor
    reshaped_tensor = image_tensor.reshape(1, 9)

    # 2. Transpose the tensor
    transposed_tensor = image_tensor.T

    # 3. Slice the tensor
    sliced_tensor = image_tensor[:2, :2]

    # 4. Concatenate tensors
    concatenated_tensor = np.concatenate((image_tensor, image_tensor), axis=0)

    # 5. Element-wise operations
    added_tensor = image_tensor + 0.1
    multiplied_tensor = image_tensor * 2

    # 6. Reduction operations
    sum_tensor = np.sum(image_tensor)
    mean_tensor = np.mean(image_tensor, axis=0)
    max_tensor = np.max(image_tensor, axis=1)

    # 7. Indexing
    element = image_tensor[1, 2]
  ```
</details>

In [14]:
image_tensor = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

In [15]:
# your code here
# 1. Reshape the tensor
reshaped_tensor = image_tensor.reshape(1, 9)

# 2. Transpose the tensor
transposed_tensor = image_tensor.T

# 3. Slice the tensor
sliced_tensor = image_tensor[:2, :2]

# 4. Concatenate tensors
concatenated_tensor = np.concatenate((image_tensor, image_tensor), axis=0)

# 5. Element-wise operations
added_tensor = image_tensor + 0.1
multiplied_tensor = image_tensor * 2

# 6. Reduction operations
sum_tensor = np.sum(image_tensor)
mean_tensor = np.mean(image_tensor, axis=0)
max_tensor = np.max(image_tensor, axis=1)

# 7. Indexing
element = image_tensor[1, 2]